apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: helmrepo
  namespace: default
spec:
  type: HelmRepo
  pathname: https://argoproj.github.io/argo-helm
  insecureSkipVerify: true
