apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: argo-sub
spec:
  channel: default/helmrepo
  name: argo-cd
  placement:
    placementRef:
      kind: PlacementRule
      name: argo-pr
  packageFilter:
    version: "2.11.0"
  packageOverrides:
    - packageName: argo-cd
      packageAlias: argo-cd
      packageOverrides:
      - path: spec
        value:
          installCRDs: false
          global:
            image:
              tag: v1.8.1
          dex:
            enabled: false
          server:
            extraArgs:
              - --insecure
            config:
              repositories: |
                - type: helm
                  name: stable
                  url: https://charts.helm.sh/stable
                - type: helm
                  name: argo-cd
                  url: https://argoproj.github.io/argo-helm

