apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/github-branch: master
    apps.open-cluster-management.io/github-path: argoconfig
  name: argoconfig-sub
spec:
  channel: gitops-chn-ns/gitops
  placement:
    placementRef:
      kind: PlacementRule
      name: argoconfig-pr
